### ISSUE TITLE
Lanjutan Chapter

### ISSUE THREAD

**Issue by andi-faizal94** [itsfaqih/fundamental-pemrograman#1]
Hallo mas, tulisannya menarik untuk dibaca dan dilanjutkan kembali, apakah ada lanjutannya mengenai beberapa chapter yang belum di selesaikan?

**Comment by itsfaqih** [comment]
makasih sudah membaca mas. untuk saat ini belum. akan saya lanjutkan kalau sudah ada waktu luang ya
